### ISSUE TITLE
REI support

### ISSUE THREAD

**Issue by slava110** [RealRTTV/malum-fabric#10]
Would be nice to see Malum recipes in [REI (Roughly enough items)](https://modrinth.com/mod/roughly-enough-items)
This might be helpful for you:
- [REI docs for developers](https://shedaniel.gitbook.io/roughly-enough-items/setup/gradle-setup)
- [Forge Malum JEI recipes source](https://github.com/SammySemicolon/Malum-Mod/tree/1.18.1/src/main/java/com/sammy/malum/compability/jei)
- [Conjuring REI compatibility source](https://github.com/wisp-forest/conjuring/tree/1.18.2/src/main/java/com/glisco/conjuring/compat/rei) (as an example)

**Comment by Arathain** [comment]
If we'll be providing support to any recipe viewer, it'll probably be [EMI](https://modrinth.com/mod/emi). With that said, we currently have bigger issues on our sights (porting to 1.19 & whatnot)

**Comment by RealRTTV** [comment]
adding emi support rn

**Comment by slava110** [comment]
Nice. *Is EMI compatible with REI API tho*? Most of mods in my modpack use REI API instead of EMI

**Comment by RealRTTV** [comment]
thats a great question.


so i just finished emi for the 1.18.2 branch and the 1.19 branch, they'll hopefully be releasing tomorrow

**Comment by slava110** [comment]
@RealRTTV so 1.18.2 version with EMI support won't be released on Modrinth? Should I compile it by myself?

**Comment by slava110** [comment]
Is it the right place to look for releases?
https://modrinth.com/mod/malum-quilt/versions
There's no `0.2.0+1.18.2`
Latest release (1.19):
https://modrinth.com/mod/malum-quilt/version/b1.1.1
Release with EMI support added (1.19):
https://modrinth.com/mod/malum-quilt/version/1.1.0
Latest release for 1.18.2 (but no EMI support in changelog)
https://modrinth.com/mod/malum-quilt/version/b1.0.8

**Comment by RealRTTV** [comment]
did i forget to add emi support there?

**Comment by RealRTTV** [comment]
![image](https://user-images.githubusercontent.com/72476111/175299134-1e060abb-0920-460a-8823-6887a59d5292.png)

**Comment by RealRTTV** [comment]
gotta fix that now, probably

**Comment by slava110** [comment]
Thanks!
