### ISSUE TITLE
Datapack error when loading with Create

### ISSUE THREAD

**Issue by Aquaeyes** [RealRTTV/malum-fabric#2]
[latest.log](https://github.com/RealRTTV/malum-fabric/files/8801815/latest.log)

When creating a world with Create installed alongside, a warning for _[23:43:06] [Render thread/WARN]: @ModifyConstant conflict. Skipping malum.mixins.json:SeverPlayerInteractionManagerMixin->@ModifyConstant::processBlockBreakingAction(D)D from mod malum with priority 1000, already redirected by mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin->@ModifyConstant::getActualReachDistance(D)D from mod reach-entity-attributes with priority 1000_ will appear, alongside the error in-game 'Errors in currently selected datapacks prevented the world from loading. You can either try to load with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually.' - with the Safe Mode option not doing anything.

Installed mods are

- create-mc1.18.2_v0.4.1+586
- malum-fabric-b1.0.1
- qsl-1.1.0-beta.8_qfapi-1.0.0-beta.14_fapi-0.51.1_mc-1.18.2
- trinkets-3.3.1

**Comment by RealRTTV** [comment]
yea that seems like a constants collision due to a rune requiring to extend the server reach distance, ill try to change the modifyconstant to modify g instead but it's a really tight inject, id also expect other issues to occur after this with create

**Comment by RealRTTV** [comment]
i just fixed that one, there seems to be a new one with ingredients :/

**Comment by Aquaeyes** [comment]
There also exists a smiliar error with Botania, should I make a separate issue for that despite the similarity?

**Comment by Arathain** [comment]
Sure, go ahead - post the full log as well

**Comment by Aquaeyes** [comment]
Crash on load for botania. No crash report generated.
[latest.log](https://github.com/RealRTTV/malum-fabric/files/8811538/latest.log)

**Comment by goldenapple3** [comment]
Create works fine since https://modrinth.com/mod/create-fabric/version/mc1.18.2_v0.4.1+594

**Comment by goldenapple3** [comment]
..though there is some weirdness with REI if Malum is installed

**Comment by RealRTTV** [comment]
is the weirdness about the item particles?

**Comment by goldenapple3** [comment]
Actually Create + Malum + REI by themselves don't do this, this is more complicated than I thought

**Comment by goldenapple3** [comment]
I was completely wrong, bisection shows that the real problem is Spectrum
