### ISSUE TITLE
Crash on startup for Botania

### ISSUE THREAD

**Issue by Aquaeyes** [RealRTTV/malum-fabric#4]
[latest.log](https://github.com/RealRTTV/malum-fabric/files/8811542/latest.log)
No crash report generated.

Installed mods are

- notenoughcrashes-4.1.6+1.18.2-fabric
- Patchouli-1.18.2-69-FABRIC
- Botania-1.18.2-432-FABRIC
- malum-fabric-b1.0.1
- qsl-1.1.0-beta.8_qfapi-1.0.0-beta.14_fapi-0.51.1_mc-1.18.2
- trinkets-3.3.1

**Comment by Arathain** [comment]
I think I know what the issue is here - will fix once I get home
