### ISSUE TITLE
Players in creative take damage

### ISSUE THREAD

**Issue by Aquaeyes** [RealRTTV/malum-fabric#5]
i am so sorry

Players in creative can take damage from, what I've tested so far:

- TNT
- Creepers
- Lava
- Anvils
- Suffocating

Not drowning, even when the breath meter is depleted.

**Comment by SammySemicolon** [comment]
Keep going at it mate, I'm sure RTTV won't cry that much :)

**Comment by RealRTTV** [comment]
fixed, there was an override to the player damage method so it flattened everything and made it act like a living entity, yay!
