### ISSUE TITLE
Throwing a Scythe with rebound into a nether portal effectively destroys the item.

### ISSUE THREAD

**Issue by Aquaeyes** [RealRTTV/malum-fabric#6]
Also, in about half the cases where I've moved away from the scythe fast enough to unload it, and moved back into the chunk, the scythe's sound plays once and then it seems to no longer exist. I can't reliably reproduce the unloading one way or the other, only the portal. A repeating command block running /say shows it disappears the moment it goes through, that, or extremely shortly after.

**Comment by RealRTTV** [comment]
im gonna assign this to arathain since he made the scythe system

**Comment by Arathain** [comment]
@Aquaeyes is this different than what happens on the forge version?

**Comment by RealRTTV** [comment]
im pretty sure I fixed this without fixing it

**Comment by RealRTTV** [comment]
alright closing this since I made scythes not able to enter portals and changing dimensions with scythes seems to cause almost no issues
