### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by goldenapple3** [RealRTTV/malum-fabric#7]
[latest.log](https://github.com/RealRTTV/malum-fabric/files/8836106/latest.log)

```
cardinal-components-api-4.1.4.jar
malum-quilt-b1.0.4.jar
qsl-1.1.0-beta.8_qfapi-1.0.0-beta.14_fapi-0.51.1_mc-1.18.2.jar
trinkets-3.3.1.jar
```
Quilt Loader 0.16.1

**Comment by RealRTTV** [comment]
you're using the wrong version since the development environment requires a mixin with a specific name while the one in production requires a different one, I've released b1.0.5 on Modrinth you can use that

**Comment by goldenapple3** [comment]
thank you for the quick fix!
