### ISSUE TITLE
Most recipes within the game don't show up in REI when Spectrum is installed

### ISSUE THREAD

**Issue by goldenapple3** [RealRTTV/malum-fabric#8]
**Describe the bug**
* A lot of crafting recipes (incl. vanilla and other mods) stop showing up in REI when Spectrum and Malum are both installed.
* This seems to apply only to some categories of recipes (e.g. Automated Shaped/Shapeless Crafting and Bulk Blasting from Create always shows, which I guess is kind of a workaround, even when most workbench and furnace recipes don't work)
* Not all recipes in that category are affected but most are
* Recipes themselves still work

**Mod version**
```
architectury-4.4.68.jar
cloth-config-6.2.57-fabric.jar
malum-quilt-b1.0.6.jar
owo-lib-0.7.2+1.18.jar
Patchouli-1.18.2-69-FABRIC.jar
qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2.jar
RoughlyEnoughItems-8.2.471.jar
spectrum-1.4.0-1.18.2-chaos-and-exploration.jar
trinkets-3.3.1.jar
```

**Screenshots**
![rei screenshot](https://user-images.githubusercontent.com/53568168/172465362-77cd85f4-4b4c-4a49-aee1-17d456412b43.png)
Block of Copper only shows scraping recipes

I cross-posted this to https://github.com/DaFuqs/Spectrum/issues/62 because I don't know which mod is to blame for this. Taking out one of the mods solves the issue.

**Comment by RealRTTV** [comment]
What's the second tab for at the top?

**Comment by RealRTTV** [comment]
so what should be there?

**Comment by RealRTTV** [comment]
found it, ill be releasing b1.0.7 in a bit
